```{r}
library(tidyverse)
```

```{r}
    data <- read_delim("data/data_csv.csv", delim = ",", n_max = 10)

    data$Группа <- factor(data$Группа)
    data$Пол <- factor(data$Пол)
    data$'Группа крови' <- factor(data$ 'Группа крови') 
    data
```

```{r}
write_delim(data, "out/data_csv.csv", delim = ",")
list.files("out")
```

```{r}
    data <- read_tsv("data/data_tsv.tsv")

    data
```

```{r}
tibble(var_first = 1:10,
 var_second = ifelse(var_first < 5, var_first + 100, var_first)
 )
 ```
 

```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

data
```

```{r}

data |> mutate(across(!contains("E1"), function(x) str_c(x, " + некая строка")))
```

```{r}
library(tidyverse)
library(flextable)

data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

table <- data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)

table |>
  flextable()
```

```{r}
table |>
  flextable() |>
theme_alafoli()
```